CREATE TABLE products (
id INT AUTO_INCREMENT PRIMARY KEY,
product_name VARCHAR(255) NOT NULL,
product_desc VARCHAR(255),
img VARCHAR(255),
category VARCHAR(255) NOT NULL,
price INT NOT NULL,
stock INT NOT NULL);
